src/airflow_dags/dags/uk/forecast-gsp-dag.py
Replicates https://github.com/openclimatefix/ocf-infrastructure/pull/829
=> fix(forcast-dag): Add in James' changes from terraform

src/airflow_dags/dags/uk/forecast-gsp-dag.py
- copy over odd log
- always run blend, even in pvnet fails, this is becasue some models might be sucessful
Fixes #50 
CI tests
=> update message, and always trigger blend

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Change trigger rule to all_done for blend service
=> 50 pvnet log

src/airflow_dags/dags/uk/forecast-national-dag.py
- fixed NESO forecast logs name
=> fix spelling

src/airflow_dags/dags/uk/forecast-national-dag.py
=> Fix neso forecast logs

src/airflow_dags/dags/uk/forecast-gsp-dag.py
=> fix(uk-forecast): Differences between prod and live

src/airflow_dags/dags/india/consume-nwp-dag.py, src/airflow_dags/dags/india/consume-runvnl-dag.py, src/airflow_dags/dags/india/consume-sat-dag.py, src/airflow_dags/dags/india/forecast-site-dag.py, src/airflow_dags/dags/india/manage-elasticbeanstalk-dag.py, src/airflow_dags/dags/uk/consume-neso-dag.py, src/airflow_dags/dags/uk/consume-nwp-dag.py, src/airflow_dags/dags/uk/consume-pv-dag.py, src/airflow_dags/dags/uk/consume-pvlive-dag.py, src/airflow_dags/dags/uk/consume-sat-dag.py, src/airflow_dags/dags/uk/forecast-clouds-dag.py, src/airflow_dags/dags/uk/forecast-gsp-dag.py, src/airflow_dags/dags/uk/forecast-site-dag.py, src/airflow_dags/dags/uk/manage-elasticbeanstalk-dag.py, src/airflow_dags/dags/uk/metrics-dag.py, src/airflow_dags/dags/uk/satellite-dag.py, tests/test_import.py
Decided that all the tags did was reduce the information densitty on the UI. Instead, opted for a consistent name scheme of the DAGs for quick parsing of funciton.
=> style(dags): Remove tags

src/airflow_dags/dags/uk/consume-nwp-dag.py
Upgrade nwp consumer to 1.1.9
CI tests
=> 1.1.9 nwp consumer

src/airflow_dags/dags/uk/consume-nwp-dag.py
=> CPU 1024 for nwp consumer

src/airflow_dags/dags/uk/consume-nwp-dag.py
Only run one nwp consumer at once
=> only run one nwp consumer at once

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade pvnet to 2.5.15
Fixes #
CI tests
=> pvnet 2.5.15

src/airflow_dags/dags/uk/consume-nwp-dag.py
nwp conusmer 1.1.14, and cpu to 1024 and memoery to 2048
Fixes #
ran on dev
=> 1.1.14 nwp

src/airflow_dags/dags/uk/consume-nwp-dag.py
=> Upgrade nwp

src/airflow_dags/dags/uk/consume-nwp-dag.py, src/airflow_dags/dags/uk/consume-sat-dag.py
- comment out new satellite conusmer
- nwp consumer 1.1.15
Fixes #
CI tests
=> nwp 1.1.15

src/airflow_dags/dags/uk/consume-nwp-dag.py
update nwp to 1.1.18
Fixes #
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_
=> Nwp 1.1.16

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade blend to 1.1.0 - dynamic blending
CI tests
=> blend 1.1.0

src/airflow_dags/dags/uk/forecast-gsp-dag.py
I've created a new container definition to run PVNet+cloudcasting from the branch openclimatefix/uk-pvnet-app#302
It might be long time before we are ready to run this version of PVNet in production, hence I've written this PR so that it will run the old PVNet version on production even if this version of the airflow dags is pushed to the production environment.
=> Update dev-only to run cloudcasting

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Revert #164 
This PR is breaking on dev with an unhelpful error. Let's not leave it broken for the weekend
=> Revert #164

src/airflow_dags/dags/uk/consume-ned-nl-dag.py, src/airflow_dags/plugins/operators/ecs_run_task_operator.py, tests/test_import.py
- add ned nl solar consumer
- putting this in uk for the moment, will change when more mature, but change domain to allow nl. Note later plan is to change nowcasting to europe
#159
=> add ned-nl consumer

src/airflow_dags/dags/uk/consume-pvlive-dag.py
- moves to new url
- gets 342 gsps
Need to merge https://github.com/openclimatefix/pvlive-consumer/pull/100 first
=> update to pvlive

src/airflow_dags/dags/uk/forecast-gsp-dag.py
- add custom warning and error message based of when a forecast was last made
#148
=> pvnet warning and error

src/airflow_dags/dags/uk/consume-pvlive-dag.py
Role back PVlive to old
Fixes #
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Please also list any relevant details for your test configuration_
_If your changes affect data processing, have you plotted any changes? i.e. have you done a quick sanity check?_
=> role back pvlive

README.md
Add a section on how to make a release
Ci tests
=> add how to make a realease

src/airflow_dags/dags/uk/consume-ned-nl-dag.py, src/airflow_dags/dags/uk/forecast-ned-nl-dag.py, tests/test_import.py
- add Ned NL solar forecat
Needs https://github.com/openclimatefix/solar-consumer/pull/64 first
=> add ned nl solar forecast

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Use pvnet app 2.5.17, this fixes the dirty version, which was having some odd effects - https://github.com/openclimatefix/nowcasting-metrics/issues/58
CI tests
=> use pvnet 2.5.17

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade pvnet to 2.5.18
[Fixes #](https://github.com/openclimatefix/nowcasting-metrics/issues/58)
CI tests
=>  pvnet to 2.5.18

src/airflow_dags/dags/uk/consume-ned-nl-dag.py, src/airflow_dags/dags/uk/forecast-ned-nl-dag.py
- Update ned nl consumer and forecast to 1.1.6
CI tests
=> ned nl 1.1.6

src/airflow_dags/dags/uk/forecast-gsp-dag.py
=> blend 1.1.2

src/airflow_dags/dags/uk/forecast-site-dag.py
Update site db clean up to 1.0.30
Fixes #
CI tests
=> site-clean-1.0.30

src/airflow_dags/dags/uk/consume-nwp-nl-dag.py
Update name of nwp nl consumer, so it doesnt cross over with uk onw
=> Update nl nwp consumer

src/airflow_dags/dags/uk/forecast-site-nl-dag.py, tests/test_import.py
Add nl site forecast, just running it every 6 hours from 2 and 3 in the morning. Need more NWP data, before it works more
CI tests
=> Nl forecast

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Update to pvnet 2.5.21
Fixes #
Ci tests
=> Fix gsp forecast

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade blend to 1.1.4 - its got improved logging
Fixes #
CI tests
=> blend 1.1.4

src/airflow_dags/dags/uk/metrics-dag.py
Update metrics, should be faster save method
=> metric 1.2.26

src/airflow_dags/dags/uk/api-national-gsp-check.py, tests/test_import.py
Add api checks
- This helps identifies any broke routes
- Helps checks speeds on routes
- Already identified a problem (and now solved) https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/453
- Currently no slack message if something is broken, but I thought we could add that afterwards, once we are happy with the behaviour
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/438
=> add apis checks

src/airflow_dags/dags/uk/forecast-gsp-dag.py
- This updates the GSP day-ahead model to use the uk-pvnet-app dev branch image
- Also correct some environmental variables
- Also some tidying
=> Update the dev day-ahead model + tidy

src/airflow_dags/dags/uk/forecast-gsp-dag.py
=> fix duplicate container name

src/airflow_dags/dags/uk/api-national-gsp-check.py
- check national forecast, with true and false metadata
- add __main__ to locally run it
#224
=> add new check, comparing national forecast with and without metadata

README.md
release 1.6.0, so just update readme.md
- add API UAT check
- upgrade pvnet to 2.6.0, new gsps models
=> release 1.6.0 #minor

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Update blend to 1.1.5, save horizon_minutes
- CI tests
=> 1.1.5 blend

src/airflow_dags/dags/uk/metrics-dag.py
=> metrics 1.3.4

src/airflow_dags/dags/uk/forecast-site-nl-dag.py
- run new NL model
- run every hour
CI tests
=> NL forecast 0.0.18

src/airflow_dags/dags/india/consume-nwp-dag.py, src/airflow_dags/dags/india/consume-runvnl-dag.py, src/airflow_dags/dags/india/consume-sat-dag.py, src/airflow_dags/dags/india/forecast-site-dag.py, src/airflow_dags/dags/india/manage-elasticbeanstalk-dag.py, src/airflow_dags/dags/uk/api-national-gsp-check.py, src/airflow_dags/dags/uk/consume-ned-nl-dag.py, src/airflow_dags/dags/uk/consume-neso-dag.py, src/airflow_dags/dags/uk/consume-nwp-dag.py, src/airflow_dags/dags/uk/consume-nwp-nl-dag.py, src/airflow_dags/dags/uk/consume-pv-dag.py, src/airflow_dags/dags/uk/consume-pvlive-dag.py, src/airflow_dags/dags/uk/consume-sat-dag.py, src/airflow_dags/dags/uk/forecast-clouds-dag.py, src/airflow_dags/dags/uk/forecast-gsp-dag.py, src/airflow_dags/dags/uk/forecast-site-dag.py, src/airflow_dags/dags/uk/forecast-site-nl-dag.py, src/airflow_dags/dags/uk/metrics-dag.py, src/airflow_dags/plugins/callbacks/slack.py, src/airflow_dags/plugins/operators/ecs_run_task_operator.py, src/airflow_dags/plugins/scripts/elastic_beanstalk.py, src/airflow_dags/plugins/scripts/s3.py, tests/test_import.py
This PR updates the `on_failure_callback` messages across the DAGs to include country flags, making the alerts more visually informative and easier to identify at a glance. No core logic or functionality was altered—this is a purely cosmetic improvement for better readability.
Fixes #246 
Manually verified that the country flags render correctly in the UI for all supported countries.
No automated tests added, as this was a purely visual/static UI enhancement.
=> Add country flags to slack

src/airflow_dags/dags/uk/forecast-site-nl-dag.py
Update nl site forecast to 0.0.22
=> site forecast nl 0.0.22

src/airflow_dags/dags/uk/consume-ned-nl-dag.py
- run latest ned-nl consumer
- run consumer eveyr 15 minutes
=> ned-consumer-0.0.14-every-15

README.md
- Add country flags to slack messages
- PVNet to `2.6.3`, save forecast horizon
- NL forecast to `0.0.22`
- NedNL Consumer to `1.1.14` and run every 30 mins
- Upgrade NedNl Forecast to `1.1.14`
Satellite consumer is still on satip
=> release 1.9.0

src/airflow_dags/dags/uk/consume-ned-nl-dag.py, src/airflow_dags/dags/uk/consume-pv-dag.py, src/airflow_dags/dags/uk/forecast-site-dag.py, src/airflow_dags/dags/uk/forecast-site-nl-dag.py
Upgrades
pv consumer - 2.2.0
solar consumer - 1.2.0
pv-site-production - 1.1.0
database-cleanup - 1.1.0
site-forecast-app - 1.1.0
Helps with https://github.com/openclimatefix/pv-site-datamodel/issues/104
- TODO tested manually on dev
=> upgrade for site database

src/airflow_dags/dags/uk/consume-ned-nl-dag.py
=> nl consumer 1.2.1

src/airflow_dags/dags/india/forecast-site-dag.py
=> Update container tag

src/airflow_dags/dags/uk/check-api-site.py
Only check forecast in site api, dont check generation
needed for https://github.com/openclimatefix/airflow-dags/issues/271
ran on dev
=> dont check for generation

README.md
All: Add links to airflow in slack messages #278 
UK:
- Add new satellite consumer (helps with #145 )
- Change Site API not to check generation values
=> Release 1.12.0

src/airflow_dags/dags/uk/consume-pvlive-dag.py
=> feat: Default 12 hours of PVLive history for in-day consumer

src/airflow_dags/plugins/scripts/s3.py
- fix method of extract and saving to zarr.zip
#145
=> fix for saving to zarr.zip

src/airflow_dags/dags/india/forecast-site-dag.py, src/airflow_dags/dags/uk/forecast-site-nl-dag.py
use site-forecast-app 1.1.10
- CI test
=> site forecast app 1.1.10

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade pvnet app to 2.6.7
CI test
=> pvnet-app 2.6.7

README.md
UK
- PVNet app `2.6.8`, Update Pvnet and PVnet summation models
- PVLive Consumer gets 12 hours of history. 
- Add Fix ice chunk location for new satellite consumer
- Add 0 degree satellite in new satellite consumer
NL
- Update site forecast to `1.1.10`, read for new satellite consumer
- Save ML batches
- CI tests
- tested on dev for > 3 days
=> update read me #minor

src/airflow_dags/dags/uk/forecast-site-nl-dag.py
- Add Back up satellite for nl consumer
- ci tests
- tested on dev yesterady with 15 minute data
=> Nl 15 minute satellite

README.md
- Update NL site forecast to `1.1.11`, works with backup satellite data
- CI test
- tested on dev for a few hours while backup satellite (15 mintes 0 degree) is being used
=> release 1.15.0

src/airflow_dags/dags/uk/consume-sat-dag.py
Update new satellite consumer to save in rss dir, not testdata
Ci tests
=> save rss data (not in testdata dir)

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Update the version of the UK PVNet app to the latest one which includes a PVNet+cloudcasting model
=> Upgrade uk-pvnet-app

src/airflow_dags/dags/uk/forecast-site-nl-dag.py
Upgrade site forecast to 1.1.13, fix for https://github.com/openclimatefix/site-forecast-app/issues/57
- Ci test
- ran this locally
=> NL site forecast 1.1.13

src/airflow_dags/dags/uk/forecast-gsp-dag.py
Upgrade pvnet app to new satellite
#145
=> PVnet: update for new satellite

README.md
UK
- Change PVlive logs to INFO
- Remove old Satellite consumer
- Update blend logs to INFO
India
- Update to use new satellite consumer
- Forecast app to `1.1.16` to use new satellite consumer
#325
Helps with https://github.com/openclimatefix/ocf-infrastructure/issues/893
=> releas 1.1.17

src/airflow_dags/dags/india/consume-nwp-dag.py, src/airflow_dags/dags/uk/forecast-gsp-dag.py
Following on from, #363, but running CI
- CI
=> Update warning and error messages to include PVNet DA checks (#363)

src/airflow_dags/dags/uk/check-api-national-gsp.py
=> checks are added (#373)

src/airflow_dags/dags/india/forecast-site-dag.py
Updating site-forecast-app version for AD forecaster
=> Update ad forecast version

README.md
=> Update README release 1.22

src/airflow_dags/dags/india/forecast-site-dag.py
Updating site-forecast-app version for ad to use new location id mappings in old models
=> Update container tag version
